// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_MAINSCREEN_H
#define UI_MAINSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_MainScreen
extern void ui_MainScreen_screen_init(void);
extern void ui_MainScreen_screen_destroy(void);
extern lv_obj_t * ui_MainScreen;
extern lv_obj_t * ui_Image5;
extern void ui_event_ButtonMenu(lv_event_t * e);
extern lv_obj_t * ui_ButtonMenu;
extern lv_obj_t * ui_LabelMenu;
extern void ui_event_MainSpeedArc(lv_event_t * e);
extern lv_obj_t * ui_MainSpeedArc;
extern lv_obj_t * ui_MainSpeedNeedle;
extern lv_obj_t * ui_ContainerBat;
extern lv_obj_t * ui_MainSpeed;
extern lv_obj_t * ui_ImgScull;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_Label6;
extern lv_obj_t * ui_Label7;
extern lv_obj_t * ui_Bar1;
extern void ui_event_Button2(lv_event_t * e);
extern lv_obj_t * ui_Button2;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

