// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t * ui_MainScreen;
lv_obj_t * ui_ButtonMenu1;
lv_obj_t * ui_Label6;
lv_obj_t * ui_PanelTime;
lv_obj_t * ui_timeNTP;
lv_obj_t * ui_labelTimeIco;
lv_obj_t * ui_Container11;
lv_obj_t * ui_PanelHeatBoard3;
lv_obj_t * ui_Arc3;
lv_obj_t * ui_Label10;
lv_obj_t * ui_labelPHBcelsius1;
lv_obj_t * ui_labelPHBicoTemp1;
lv_obj_t * ui_labelPHBicoTemp3;
lv_obj_t * ui_temperatureTerra1;
lv_obj_t * ui_PanelHeatBoard4;
lv_obj_t * ui_Arc4;
lv_obj_t * ui_humityTerra;
lv_obj_t * ui_labelPHumityBicoHumity;
lv_obj_t * ui_labelPHumityBcelsius1;
lv_obj_t * ui_PanelHeatBoard;
lv_obj_t * ui_labelPHBcelsius;
lv_obj_t * ui_temperatureTerra;
lv_obj_t * ui_labelPHBicoTemp;
lv_obj_t * ui_labelPHBicoHeating;
lv_obj_t * ui_Arc1;
lv_obj_t * ui_Label8;

// event funtions
void ui_event_ButtonMenu1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_ScreenMenu, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_ScreenMenu_screen_init);
    }
}

// build funtions

void ui_MainScreen_screen_init(void)
{
    ui_MainScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_MainScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_MainScreen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MainScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_MainScreen, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_MainScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_MainScreen, &ui_font_FontAwesomepro6light30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonMenu1 = lv_btn_create(ui_MainScreen);
    lv_obj_set_width(ui_ButtonMenu1, 49);
    lv_obj_set_height(ui_ButtonMenu1, 36);
    lv_obj_set_x(ui_ButtonMenu1, -87);
    lv_obj_set_y(ui_ButtonMenu1, 132);
    lv_obj_set_align(ui_ButtonMenu1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonMenu1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonMenu1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ButtonMenu1, lv_color_hex(0x111111), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonMenu1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_ButtonMenu1, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ButtonMenu1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label6 = lv_label_create(ui_ButtonMenu1);
    lv_obj_set_width(ui_Label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label6, "");
    lv_obj_set_style_text_color(ui_Label6, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label6, &ui_font_FontAwesomepro6light20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelTime = lv_obj_create(ui_MainScreen);
    lv_obj_set_width(ui_PanelTime, 230);
    lv_obj_set_height(ui_PanelTime, 54);
    lv_obj_set_align(ui_PanelTime, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_PanelTime, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PanelTime, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PanelTime, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelTime, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PanelTime, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PanelTime, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_timeNTP = lv_label_create(ui_PanelTime);
    lv_obj_set_width(ui_timeNTP, 147);
    lv_obj_set_height(ui_timeNTP, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_timeNTP, -13);
    lv_obj_set_y(ui_timeNTP, 1);
    lv_obj_set_align(ui_timeNTP, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_timeNTP, "00:00");
    lv_obj_set_style_text_color(ui_timeNTP, lv_color_hex(0xC8C8C8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_timeNTP, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_timeNTP, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_timeNTP, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_timeNTP, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_timeNTP, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_timeNTP, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_timeNTP, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_labelTimeIco = lv_label_create(ui_PanelTime);
    lv_obj_set_width(ui_labelTimeIco, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labelTimeIco, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_labelTimeIco, -88);
    lv_obj_set_y(ui_labelTimeIco, 0);
    lv_obj_set_align(ui_labelTimeIco, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelTimeIco, "");
    lv_obj_set_style_text_color(ui_labelTimeIco, lv_color_hex(0x5A595A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_labelTimeIco, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_labelTimeIco, &ui_font_FontAwesomepro6light20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container11 = lv_obj_create(ui_MainScreen);
    lv_obj_remove_style_all(ui_Container11);
    lv_obj_set_width(ui_Container11, 232);
    lv_obj_set_height(ui_Container11, 217);
    lv_obj_set_x(ui_Container11, 0);
    lv_obj_set_y(ui_Container11, -5);
    lv_obj_set_align(ui_Container11, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container11, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_PanelHeatBoard3 = lv_obj_create(ui_Container11);
    lv_obj_set_width(ui_PanelHeatBoard3, 230);
    lv_obj_set_height(ui_PanelHeatBoard3, 70);
    lv_obj_set_align(ui_PanelHeatBoard3, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelHeatBoard3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PanelHeatBoard3, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PanelHeatBoard3, lv_color_hex(0x232323), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelHeatBoard3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_PanelHeatBoard3, lv_color_hex(0x111111), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_PanelHeatBoard3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_PanelHeatBoard3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_PanelHeatBoard3, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PanelHeatBoard3, lv_color_hex(0x2A2A2A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PanelHeatBoard3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PanelHeatBoard3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Arc3 = lv_arc_create(ui_PanelHeatBoard3);
    lv_obj_set_width(ui_Arc3, 60);
    lv_obj_set_height(ui_Arc3, 60);
    lv_obj_set_x(ui_Arc3, -69);
    lv_obj_set_y(ui_Arc3, 4);
    lv_obj_set_align(ui_Arc3, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Arc3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                      LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE);     /// Flags
    lv_arc_set_range(ui_Arc3, 0, 50);
    lv_arc_set_value(ui_Arc3, 30);
    lv_obj_set_style_arc_color(ui_Arc3, lv_color_hex(0x5A5A5A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_Arc3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_Arc3, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_Arc3, lv_color_hex(0xE6BE7B), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_Arc3, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_Arc3, 8, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Arc3, lv_color_hex(0xAF8134), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Arc3, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Arc3, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_Label10 = lv_label_create(ui_PanelHeatBoard3);
    lv_obj_set_width(ui_Label10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label10, 22);
    lv_obj_set_y(ui_Label10, 18);
    lv_obj_set_align(ui_Label10, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label10, "terarium");
    lv_obj_set_style_text_font(ui_Label10, &ui_font_roboto14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_labelPHBcelsius1 = lv_label_create(ui_PanelHeatBoard3);
    lv_obj_set_width(ui_labelPHBcelsius1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labelPHBcelsius1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_labelPHBcelsius1, 81);
    lv_obj_set_y(ui_labelPHBcelsius1, -15);
    lv_obj_set_align(ui_labelPHBcelsius1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelPHBcelsius1, "°C");
    lv_obj_set_style_text_color(ui_labelPHBcelsius1, lv_color_hex(0x999999), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_labelPHBcelsius1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_labelPHBcelsius1, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_labelPHBicoTemp1 = lv_label_create(ui_PanelHeatBoard3);
    lv_obj_set_width(ui_labelPHBicoTemp1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labelPHBicoTemp1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_labelPHBicoTemp1, -56);
    lv_obj_set_y(ui_labelPHBicoTemp1, -7);
    lv_obj_set_align(ui_labelPHBicoTemp1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelPHBicoTemp1, "");
    lv_obj_add_flag(ui_labelPHBicoTemp1, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_text_color(ui_labelPHBicoTemp1, lv_color_hex(0xF1C882), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_labelPHBicoTemp1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_labelPHBicoTemp1, &ui_font_FontAwesomepro6lightSmall, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_labelPHBicoTemp3 = lv_label_create(ui_PanelHeatBoard3);
    lv_obj_set_width(ui_labelPHBicoTemp3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labelPHBicoTemp3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_labelPHBicoTemp3, -69);
    lv_obj_set_y(ui_labelPHBicoTemp3, 8);
    lv_obj_set_align(ui_labelPHBicoTemp3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelPHBicoTemp3, "");
    lv_obj_set_style_text_color(ui_labelPHBicoTemp3, lv_color_hex(0xF1C882), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_labelPHBicoTemp3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_labelPHBicoTemp3, &ui_font_FontAwesomepro6light30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_temperatureTerra1 = lv_label_create(ui_PanelHeatBoard3);
    lv_obj_set_width(ui_temperatureTerra1, 127);
    lv_obj_set_height(ui_temperatureTerra1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_temperatureTerra1, 0);
    lv_obj_set_y(ui_temperatureTerra1, -10);
    lv_obj_set_align(ui_temperatureTerra1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_temperatureTerra1, "20,5");
    lv_obj_clear_flag(ui_temperatureTerra1,
                      LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE);     /// Flags
    lv_obj_set_style_text_color(ui_temperatureTerra1, lv_color_hex(0xC8C8C8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_temperatureTerra1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_temperatureTerra1, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_temperatureTerra1, &lv_font_montserrat_34, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_temperatureTerra1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_temperatureTerra1, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_temperatureTerra1, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_temperatureTerra1, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelHeatBoard4 = lv_obj_create(ui_Container11);
    lv_obj_set_width(ui_PanelHeatBoard4, 230);
    lv_obj_set_height(ui_PanelHeatBoard4, 70);
    lv_obj_set_align(ui_PanelHeatBoard4, LV_ALIGN_BOTTOM_MID);
    lv_obj_clear_flag(ui_PanelHeatBoard4, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PanelHeatBoard4, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PanelHeatBoard4, lv_color_hex(0x232323), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelHeatBoard4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_PanelHeatBoard4, lv_color_hex(0x111111), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_PanelHeatBoard4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_PanelHeatBoard4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_PanelHeatBoard4, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PanelHeatBoard4, lv_color_hex(0x2A2A2A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PanelHeatBoard4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PanelHeatBoard4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Arc4 = lv_arc_create(ui_PanelHeatBoard4);
    lv_obj_set_width(ui_Arc4, 60);
    lv_obj_set_height(ui_Arc4, 60);
    lv_obj_set_x(ui_Arc4, -69);
    lv_obj_set_y(ui_Arc4, 4);
    lv_obj_set_align(ui_Arc4, LV_ALIGN_CENTER);
    lv_obj_add_state(ui_Arc4, LV_STATE_USER_1);       /// States
    lv_obj_clear_flag(ui_Arc4, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    lv_arc_set_value(ui_Arc4, 50);
    lv_obj_set_style_arc_color(ui_Arc4, lv_color_hex(0x5A5A5A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_Arc4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_Arc4, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_width(ui_Arc4, 8, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Arc4, lv_color_hex(0xAF8134), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Arc4, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Arc4, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_humityTerra = lv_label_create(ui_PanelHeatBoard4);
    lv_obj_set_width(ui_humityTerra, 127);
    lv_obj_set_height(ui_humityTerra, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_humityTerra, 0);
    lv_obj_set_y(ui_humityTerra, -10);
    lv_obj_set_align(ui_humityTerra, LV_ALIGN_CENTER);
    lv_label_set_text(ui_humityTerra, "50");
    lv_obj_set_style_text_color(ui_humityTerra, lv_color_hex(0xC8C8C8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_humityTerra, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_humityTerra, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_humityTerra, &lv_font_montserrat_34, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_humityTerra, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_humityTerra, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_humityTerra, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_humityTerra, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_labelPHumityBicoHumity = lv_label_create(ui_PanelHeatBoard4);
    lv_obj_set_width(ui_labelPHumityBicoHumity, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labelPHumityBicoHumity, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_labelPHumityBicoHumity, -68);
    lv_obj_set_y(ui_labelPHumityBicoHumity, 4);
    lv_obj_set_align(ui_labelPHumityBicoHumity, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelPHumityBicoHumity, "");
    lv_obj_set_style_text_color(ui_labelPHumityBicoHumity, lv_color_hex(0x3F50FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_labelPHumityBicoHumity, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_labelPHumityBicoHumity, &ui_font_FontAwesomepro6light30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_labelPHumityBcelsius1 = lv_label_create(ui_PanelHeatBoard4);
    lv_obj_set_width(ui_labelPHumityBcelsius1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labelPHumityBcelsius1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_labelPHumityBcelsius1, 81);
    lv_obj_set_y(ui_labelPHumityBcelsius1, -15);
    lv_obj_set_align(ui_labelPHumityBcelsius1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelPHumityBcelsius1, "%");
    lv_obj_set_style_text_color(ui_labelPHumityBcelsius1, lv_color_hex(0x999999), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_labelPHumityBcelsius1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_labelPHumityBcelsius1, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelHeatBoard = lv_obj_create(ui_Container11);
    lv_obj_set_width(ui_PanelHeatBoard, 230);
    lv_obj_set_height(ui_PanelHeatBoard, 70);
    lv_obj_set_align(ui_PanelHeatBoard, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_PanelHeatBoard, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PanelHeatBoard, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PanelHeatBoard, lv_color_hex(0x232323), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelHeatBoard, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_PanelHeatBoard, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PanelHeatBoard, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_labelPHBcelsius = lv_label_create(ui_PanelHeatBoard);
    lv_obj_set_width(ui_labelPHBcelsius, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labelPHBcelsius, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_labelPHBcelsius, 81);
    lv_obj_set_y(ui_labelPHBcelsius, -15);
    lv_obj_set_align(ui_labelPHBcelsius, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelPHBcelsius, "°C");
    lv_obj_set_style_text_color(ui_labelPHBcelsius, lv_color_hex(0x999999), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_labelPHBcelsius, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_labelPHBcelsius, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_temperatureTerra = lv_label_create(ui_PanelHeatBoard);
    lv_obj_set_width(ui_temperatureTerra, 127);
    lv_obj_set_height(ui_temperatureTerra, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_temperatureTerra, 0);
    lv_obj_set_y(ui_temperatureTerra, -10);
    lv_obj_set_align(ui_temperatureTerra, LV_ALIGN_CENTER);
    lv_label_set_text(ui_temperatureTerra, "20,5");
    lv_obj_set_style_text_color(ui_temperatureTerra, lv_color_hex(0xC8C8C8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_temperatureTerra, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_temperatureTerra, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_temperatureTerra, &lv_font_montserrat_34, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_temperatureTerra, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_temperatureTerra, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_temperatureTerra, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_temperatureTerra, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_labelPHBicoTemp = lv_label_create(ui_PanelHeatBoard);
    lv_obj_set_width(ui_labelPHBicoTemp, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labelPHBicoTemp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_labelPHBicoTemp, -68);
    lv_obj_set_y(ui_labelPHBicoTemp, 8);
    lv_obj_set_align(ui_labelPHBicoTemp, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelPHBicoTemp, "");
    lv_obj_set_style_text_color(ui_labelPHBicoTemp, lv_color_hex(0xF1C882), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_labelPHBicoTemp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_labelPHBicoTemp, &ui_font_FontAwesomepro6light30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_labelPHBicoHeating = lv_label_create(ui_PanelHeatBoard);
    lv_obj_set_width(ui_labelPHBicoHeating, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labelPHBicoHeating, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_labelPHBicoHeating, 99);
    lv_obj_set_y(ui_labelPHBicoHeating, 15);
    lv_obj_set_align(ui_labelPHBicoHeating, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelPHBicoHeating, "");
    lv_obj_add_flag(ui_labelPHBicoHeating, LV_OBJ_FLAG_EVENT_BUBBLE);     /// Flags
    lv_obj_set_style_text_color(ui_labelPHBicoHeating, lv_color_hex(0xE6BE7B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_labelPHBicoHeating, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_labelPHBicoHeating, &ui_font_FontAwesomepro6light20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Arc1 = lv_arc_create(ui_PanelHeatBoard);
    lv_obj_set_width(ui_Arc1, 60);
    lv_obj_set_height(ui_Arc1, 60);
    lv_obj_set_x(ui_Arc1, -69);
    lv_obj_set_y(ui_Arc1, 4);
    lv_obj_set_align(ui_Arc1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Arc1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_GESTURE_BUBBLE);      /// Flags
    lv_arc_set_range(ui_Arc1, 0, 50);
    lv_arc_set_value(ui_Arc1, 20);
    lv_obj_set_style_arc_color(ui_Arc1, lv_color_hex(0x5A5A5A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_Arc1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_Arc1, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_Arc1, lv_color_hex(0xE6BE7B), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_Arc1, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_Arc1, 8, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Arc1, lv_color_hex(0xAF8134), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Arc1, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Arc1, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_Label8 = lv_label_create(ui_PanelHeatBoard);
    lv_obj_set_width(ui_Label8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label8, 34);
    lv_obj_set_y(ui_Label8, 18);
    lv_obj_set_align(ui_Label8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label8, "topná deska");
    lv_obj_set_style_text_font(ui_Label8, &ui_font_roboto14, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_ButtonMenu1, ui_event_ButtonMenu1, LV_EVENT_ALL, NULL);

}

void ui_MainScreen_screen_destroy(void)
{
    if(ui_MainScreen) lv_obj_del(ui_MainScreen);

    // NULL screen variables
    ui_MainScreen = NULL;
    ui_ButtonMenu1 = NULL;
    ui_Label6 = NULL;
    ui_PanelTime = NULL;
    ui_timeNTP = NULL;
    ui_labelTimeIco = NULL;
    ui_Container11 = NULL;
    ui_PanelHeatBoard3 = NULL;
    ui_Arc3 = NULL;
    ui_Label10 = NULL;
    ui_labelPHBcelsius1 = NULL;
    ui_labelPHBicoTemp1 = NULL;
    ui_labelPHBicoTemp3 = NULL;
    ui_temperatureTerra1 = NULL;
    ui_PanelHeatBoard4 = NULL;
    ui_Arc4 = NULL;
    ui_humityTerra = NULL;
    ui_labelPHumityBicoHumity = NULL;
    ui_labelPHumityBcelsius1 = NULL;
    ui_PanelHeatBoard = NULL;
    ui_labelPHBcelsius = NULL;
    ui_temperatureTerra = NULL;
    ui_labelPHBicoTemp = NULL;
    ui_labelPHBicoHeating = NULL;
    ui_Arc1 = NULL;
    ui_Label8 = NULL;

}
