// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_MAINSCREEN_H
#define UI_MAINSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_MainScreen
extern void ui_MainScreen_screen_init(void);
extern void ui_MainScreen_screen_destroy(void);
extern lv_obj_t * ui_MainScreen;
extern lv_obj_t * ui_Image5;
extern lv_obj_t * ui_ContainerBat;
extern lv_obj_t * ui_ImgScull;
extern void ui_event_ButtonMenu1(lv_event_t * e);
extern lv_obj_t * ui_ButtonMenu1;
extern lv_obj_t * ui_Label6;
extern lv_obj_t * ui_PanelHeatBoard2;
extern lv_obj_t * ui_temperatureTerra2;
extern lv_obj_t * ui_labelPHBicoTemp2;
extern lv_obj_t * ui_Container11;
extern lv_obj_t * ui_PanelHeatBoard1;
extern lv_obj_t * ui_labelPHBcelsius1;
extern lv_obj_t * ui_temperatureTerra1;
extern lv_obj_t * ui_labelPHBicoTemp1;
extern lv_obj_t * ui_labelPHBicoTemp3;
extern lv_obj_t * ui_PanelHumityBoard;
extern lv_obj_t * ui_labelPHumityBcelsius1;
extern lv_obj_t * ui_humityTerra;
extern lv_obj_t * ui_labelPHumityBicoHumity;
extern lv_obj_t * ui_PanelHeatBoard;
extern lv_obj_t * ui_labelPHBcelsius;
extern lv_obj_t * ui_temperatureTerra;
extern lv_obj_t * ui_labelPHBicoTemp;
extern lv_obj_t * ui_labelPHBicoHeating;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

