// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_SCREENMENU_H
#define UI_SCREENMENU_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_ScreenMenu
extern void ui_ScreenMenu_screen_init(void);
extern void ui_ScreenMenu_screen_destroy(void);
extern lv_obj_t * ui_ScreenMenu;
extern void ui_event_Button3(lv_event_t * e);
extern lv_obj_t * ui_Button3;
extern lv_obj_t * ui_Label2;
extern void ui_event_Button1(lv_event_t * e);
extern lv_obj_t * ui_Button1;
extern lv_obj_t * ui_Label3;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

