// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t * ui_ScreenAccel;
lv_obj_t * ui_Container1;
lv_obj_t * ui_Label4;
lv_obj_t * ui_Container2;
lv_obj_t * ui_AccelLabel;
lv_obj_t * ui_AccelX;
lv_obj_t * ui_Container3;
lv_obj_t * ui_AccelLabel1;
lv_obj_t * ui_AccelY;
lv_obj_t * ui_Container4;
lv_obj_t * ui_AccelLabel2;
lv_obj_t * ui_AccelZ;
lv_obj_t * ui_Container5;
lv_obj_t * ui_AccelLabel3;
lv_obj_t * ui_GyroX;
lv_obj_t * ui_Container6;
lv_obj_t * ui_AccelLabel4;
lv_obj_t * ui_GyroY;
lv_obj_t * ui_Container7;
lv_obj_t * ui_AccelLabel5;
lv_obj_t * ui_GyroZ;
lv_obj_t * ui_Container8;
lv_obj_t * ui_AccelLabel6;
lv_obj_t * ui_Roll;
lv_obj_t * ui_Container9;
lv_obj_t * ui_AccelLabel7;
lv_obj_t * ui_Pitch;
lv_obj_t * ui_Container10;
lv_obj_t * ui_AccelLabel8;
lv_obj_t * ui_Yaw;
lv_obj_t * ui_Button4;
lv_obj_t * ui_Label5;

// event funtions
void ui_event_ScreenAccel(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SCREEN_LOADED) {
        AccelScreenLoadEvent(e);
    }
    if(event_code == LV_EVENT_SCREEN_UNLOADED) {
        AccelScreenUnloadEvent(e);
    }
}

void ui_event_Button4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_ScreenMenu, LV_SCR_LOAD_ANIM_FADE_ON, 20, 0, &ui_ScreenMenu_screen_init);
    }
}

// build funtions

void ui_ScreenAccel_screen_init(void)
{
    ui_ScreenAccel = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScreenAccel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ScreenAccel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ScreenAccel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container1 = lv_obj_create(ui_ScreenAccel);
    lv_obj_remove_style_all(ui_Container1);
    lv_obj_set_width(ui_Container1, 212);
    lv_obj_set_height(ui_Container1, 261);
    lv_obj_set_align(ui_Container1, LV_ALIGN_TOP_MID);
    lv_obj_set_flex_flow(ui_Container1, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Container1, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Container1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_row(ui_Container1, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Container1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Container1, &ui_font_FontRoboto20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label4 = lv_label_create(ui_Container1);
    lv_obj_set_width(ui_Label4, lv_pct(100));
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label4, "Accel Test");
    lv_obj_set_style_text_align(ui_Label4, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container2 = lv_obj_create(ui_Container1);
    lv_obj_remove_style_all(ui_Container2);
    lv_obj_set_width(ui_Container2, lv_pct(100));
    lv_obj_set_height(ui_Container2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Container2, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container2, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container2, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(ui_Container2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Container2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Container2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Container2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_Container2, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Container2, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_AccelLabel = lv_label_create(ui_Container2);
    lv_obj_set_width(ui_AccelLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_AccelLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_AccelLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_AccelLabel, "X");

    ui_AccelX = lv_bar_create(ui_Container2);
    lv_bar_set_range(ui_AccelX, -10000, 10000);
    lv_obj_set_height(ui_AccelX, 10);
    lv_obj_set_flex_grow(ui_AccelX, 1);
    lv_obj_set_x(ui_AccelX, 2);
    lv_obj_set_y(ui_AccelX, -59);
    lv_obj_set_align(ui_AccelX, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_AccelX, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_AccelX, lv_color_hex(0x3A3A3A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_AccelX, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_AccelX, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_AccelX, lv_color_hex(0x6D0202), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_AccelX, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_AccelX, lv_color_hex(0xD04400), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_AccelX, LV_GRAD_DIR_HOR, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_Container3 = lv_obj_create(ui_Container1);
    lv_obj_remove_style_all(ui_Container3);
    lv_obj_set_width(ui_Container3, lv_pct(100));
    lv_obj_set_height(ui_Container3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Container3, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container3, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container3, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Container3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(ui_Container3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Container3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Container3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Container3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_Container3, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Container3, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_AccelLabel1 = lv_label_create(ui_Container3);
    lv_obj_set_width(ui_AccelLabel1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_AccelLabel1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_AccelLabel1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_AccelLabel1, "Y");

    ui_AccelY = lv_bar_create(ui_Container3);
    lv_bar_set_range(ui_AccelY, -10000, 10000);
    lv_obj_set_height(ui_AccelY, 10);
    lv_obj_set_flex_grow(ui_AccelY, 1);
    lv_obj_set_x(ui_AccelY, 2);
    lv_obj_set_y(ui_AccelY, -59);
    lv_obj_set_align(ui_AccelY, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_AccelY, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_AccelY, lv_color_hex(0x3A3A3A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_AccelY, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_AccelY, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_AccelY, lv_color_hex(0x6D0202), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_AccelY, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_AccelY, lv_color_hex(0xD04400), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_AccelY, LV_GRAD_DIR_HOR, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_Container4 = lv_obj_create(ui_Container1);
    lv_obj_remove_style_all(ui_Container4);
    lv_obj_set_width(ui_Container4, lv_pct(100));
    lv_obj_set_height(ui_Container4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Container4, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container4, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container4, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Container4, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(ui_Container4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Container4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Container4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Container4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_Container4, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Container4, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_AccelLabel2 = lv_label_create(ui_Container4);
    lv_obj_set_width(ui_AccelLabel2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_AccelLabel2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_AccelLabel2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_AccelLabel2, "Z");

    ui_AccelZ = lv_bar_create(ui_Container4);
    lv_bar_set_range(ui_AccelZ, -10000, 10000);
    lv_obj_set_height(ui_AccelZ, 10);
    lv_obj_set_flex_grow(ui_AccelZ, 1);
    lv_obj_set_x(ui_AccelZ, 2);
    lv_obj_set_y(ui_AccelZ, -59);
    lv_obj_set_align(ui_AccelZ, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_AccelZ, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_AccelZ, lv_color_hex(0x3A3A3A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_AccelZ, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_AccelZ, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_AccelZ, lv_color_hex(0x6D0202), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_AccelZ, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_AccelZ, lv_color_hex(0xD04400), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_AccelZ, LV_GRAD_DIR_HOR, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_Container5 = lv_obj_create(ui_Container1);
    lv_obj_remove_style_all(ui_Container5);
    lv_obj_set_width(ui_Container5, lv_pct(100));
    lv_obj_set_height(ui_Container5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Container5, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container5, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container5, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Container5, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(ui_Container5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Container5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Container5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Container5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_Container5, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Container5, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_AccelLabel3 = lv_label_create(ui_Container5);
    lv_obj_set_width(ui_AccelLabel3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_AccelLabel3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_AccelLabel3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_AccelLabel3, "Xg");

    ui_GyroX = lv_bar_create(ui_Container5);
    lv_bar_set_range(ui_GyroX, -10000, 10000);
    lv_obj_set_height(ui_GyroX, 10);
    lv_obj_set_flex_grow(ui_GyroX, 1);
    lv_obj_set_x(ui_GyroX, 2);
    lv_obj_set_y(ui_GyroX, -59);
    lv_obj_set_align(ui_GyroX, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_GyroX, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_GyroX, lv_color_hex(0x3A3A3A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_GyroX, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_GyroX, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_GyroX, lv_color_hex(0x6D0202), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_GyroX, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_GyroX, lv_color_hex(0xD04400), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_GyroX, LV_GRAD_DIR_HOR, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_Container6 = lv_obj_create(ui_Container1);
    lv_obj_remove_style_all(ui_Container6);
    lv_obj_set_width(ui_Container6, lv_pct(100));
    lv_obj_set_height(ui_Container6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Container6, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container6, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container6, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Container6, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(ui_Container6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Container6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Container6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Container6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_Container6, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Container6, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_AccelLabel4 = lv_label_create(ui_Container6);
    lv_obj_set_width(ui_AccelLabel4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_AccelLabel4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_AccelLabel4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_AccelLabel4, "Yg");

    ui_GyroY = lv_bar_create(ui_Container6);
    lv_bar_set_range(ui_GyroY, -10000, 10000);
    lv_obj_set_height(ui_GyroY, 10);
    lv_obj_set_flex_grow(ui_GyroY, 1);
    lv_obj_set_x(ui_GyroY, 2);
    lv_obj_set_y(ui_GyroY, -59);
    lv_obj_set_align(ui_GyroY, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_GyroY, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_GyroY, lv_color_hex(0x3A3A3A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_GyroY, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_GyroY, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_GyroY, lv_color_hex(0x6D0202), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_GyroY, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_GyroY, lv_color_hex(0xD04400), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_GyroY, LV_GRAD_DIR_HOR, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_Container7 = lv_obj_create(ui_Container1);
    lv_obj_remove_style_all(ui_Container7);
    lv_obj_set_width(ui_Container7, lv_pct(100));
    lv_obj_set_height(ui_Container7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Container7, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container7, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container7, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Container7, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(ui_Container7, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Container7, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Container7, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Container7, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_Container7, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Container7, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_AccelLabel5 = lv_label_create(ui_Container7);
    lv_obj_set_width(ui_AccelLabel5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_AccelLabel5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_AccelLabel5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_AccelLabel5, "Zg");

    ui_GyroZ = lv_bar_create(ui_Container7);
    lv_bar_set_range(ui_GyroZ, -10000, 10000);
    lv_obj_set_height(ui_GyroZ, 10);
    lv_obj_set_flex_grow(ui_GyroZ, 1);
    lv_obj_set_x(ui_GyroZ, 2);
    lv_obj_set_y(ui_GyroZ, -59);
    lv_obj_set_align(ui_GyroZ, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_GyroZ, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_GyroZ, lv_color_hex(0x3A3A3A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_GyroZ, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_GyroZ, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_GyroZ, lv_color_hex(0x6D0202), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_GyroZ, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_GyroZ, lv_color_hex(0xD04400), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_GyroZ, LV_GRAD_DIR_HOR, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_Container8 = lv_obj_create(ui_Container1);
    lv_obj_remove_style_all(ui_Container8);
    lv_obj_set_width(ui_Container8, lv_pct(100));
    lv_obj_set_height(ui_Container8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Container8, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container8, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container8, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Container8, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(ui_Container8, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Container8, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Container8, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Container8, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_Container8, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Container8, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_AccelLabel6 = lv_label_create(ui_Container8);
    lv_obj_set_width(ui_AccelLabel6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_AccelLabel6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_AccelLabel6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_AccelLabel6, "Roll");

    ui_Roll = lv_bar_create(ui_Container8);
    lv_bar_set_range(ui_Roll, -180, 180);
    lv_obj_set_height(ui_Roll, 10);
    lv_obj_set_flex_grow(ui_Roll, 1);
    lv_obj_set_x(ui_Roll, 2);
    lv_obj_set_y(ui_Roll, -59);
    lv_obj_set_align(ui_Roll, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_Roll, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Roll, lv_color_hex(0x3A3A3A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Roll, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_Roll, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Roll, lv_color_hex(0x6D0202), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Roll, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Roll, lv_color_hex(0xD04400), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_Roll, LV_GRAD_DIR_HOR, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_Container9 = lv_obj_create(ui_Container1);
    lv_obj_remove_style_all(ui_Container9);
    lv_obj_set_width(ui_Container9, lv_pct(100));
    lv_obj_set_height(ui_Container9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Container9, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container9, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container9, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Container9, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(ui_Container9, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Container9, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Container9, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Container9, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_Container9, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Container9, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_AccelLabel7 = lv_label_create(ui_Container9);
    lv_obj_set_width(ui_AccelLabel7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_AccelLabel7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_AccelLabel7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_AccelLabel7, "Pitc");

    ui_Pitch = lv_bar_create(ui_Container9);
    lv_bar_set_range(ui_Pitch, -180, 180);
    lv_obj_set_height(ui_Pitch, 10);
    lv_obj_set_flex_grow(ui_Pitch, 1);
    lv_obj_set_x(ui_Pitch, 2);
    lv_obj_set_y(ui_Pitch, -59);
    lv_obj_set_align(ui_Pitch, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_Pitch, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Pitch, lv_color_hex(0x3A3A3A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Pitch, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_Pitch, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Pitch, lv_color_hex(0x6D0202), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Pitch, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Pitch, lv_color_hex(0xD04400), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_Pitch, LV_GRAD_DIR_HOR, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_Container10 = lv_obj_create(ui_Container1);
    lv_obj_remove_style_all(ui_Container10);
    lv_obj_set_width(ui_Container10, lv_pct(100));
    lv_obj_set_height(ui_Container10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Container10, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container10, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container10, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Container10, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(ui_Container10, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Container10, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Container10, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Container10, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_Container10, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Container10, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_AccelLabel8 = lv_label_create(ui_Container10);
    lv_obj_set_width(ui_AccelLabel8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_AccelLabel8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_AccelLabel8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_AccelLabel8, "Yaw");

    ui_Yaw = lv_bar_create(ui_Container10);
    lv_bar_set_range(ui_Yaw, -180, 180);
    lv_obj_set_height(ui_Yaw, 10);
    lv_obj_set_flex_grow(ui_Yaw, 1);
    lv_obj_set_x(ui_Yaw, 2);
    lv_obj_set_y(ui_Yaw, -59);
    lv_obj_set_align(ui_Yaw, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_Yaw, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Yaw, lv_color_hex(0x3A3A3A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Yaw, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_Yaw, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Yaw, lv_color_hex(0x6D0202), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Yaw, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Yaw, lv_color_hex(0xD04400), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_Yaw, LV_GRAD_DIR_HOR, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_Button4 = lv_btn_create(ui_ScreenAccel);
    lv_obj_set_width(ui_Button4, 100);
    lv_obj_set_height(ui_Button4, 50);
    lv_obj_set_align(ui_Button4, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_add_flag(ui_Button4, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Button4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Button4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Button4, lv_color_hex(0x999999), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Button4, lv_color_hex(0x999999), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Button4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Button4, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_Button4, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Button4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Button4, &ui_font_FontRoboto20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label5 = lv_label_create(ui_Button4);
    lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label5, "Back");

    lv_obj_add_event_cb(ui_Button4, ui_event_Button4, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ScreenAccel, ui_event_ScreenAccel, LV_EVENT_ALL, NULL);

}

void ui_ScreenAccel_screen_destroy(void)
{
    if(ui_ScreenAccel) lv_obj_del(ui_ScreenAccel);

    // NULL screen variables
    ui_ScreenAccel = NULL;
    ui_Container1 = NULL;
    ui_Label4 = NULL;
    ui_Container2 = NULL;
    ui_AccelLabel = NULL;
    ui_AccelX = NULL;
    ui_Container3 = NULL;
    ui_AccelLabel1 = NULL;
    ui_AccelY = NULL;
    ui_Container4 = NULL;
    ui_AccelLabel2 = NULL;
    ui_AccelZ = NULL;
    ui_Container5 = NULL;
    ui_AccelLabel3 = NULL;
    ui_GyroX = NULL;
    ui_Container6 = NULL;
    ui_AccelLabel4 = NULL;
    ui_GyroY = NULL;
    ui_Container7 = NULL;
    ui_AccelLabel5 = NULL;
    ui_GyroZ = NULL;
    ui_Container8 = NULL;
    ui_AccelLabel6 = NULL;
    ui_Roll = NULL;
    ui_Container9 = NULL;
    ui_AccelLabel7 = NULL;
    ui_Pitch = NULL;
    ui_Container10 = NULL;
    ui_AccelLabel8 = NULL;
    ui_Yaw = NULL;
    ui_Button4 = NULL;
    ui_Label5 = NULL;

}
