// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_SCREENACCEL_H
#define UI_SCREENACCEL_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_ScreenAccel
extern void ui_ScreenAccel_screen_init(void);
extern void ui_ScreenAccel_screen_destroy(void);
extern void ui_event_ScreenAccel(lv_event_t * e);
extern lv_obj_t * ui_ScreenAccel;
extern lv_obj_t * ui_Container1;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_Container2;
extern lv_obj_t * ui_AccelLabel;
extern lv_obj_t * ui_AccelX;
extern lv_obj_t * ui_Container3;
extern lv_obj_t * ui_AccelLabel1;
extern lv_obj_t * ui_AccelY;
extern lv_obj_t * ui_Container4;
extern lv_obj_t * ui_AccelLabel2;
extern lv_obj_t * ui_AccelZ;
extern lv_obj_t * ui_Container5;
extern lv_obj_t * ui_AccelLabel3;
extern lv_obj_t * ui_GyroX;
extern lv_obj_t * ui_Container6;
extern lv_obj_t * ui_AccelLabel4;
extern lv_obj_t * ui_GyroY;
extern lv_obj_t * ui_Container7;
extern lv_obj_t * ui_AccelLabel5;
extern lv_obj_t * ui_GyroZ;
extern lv_obj_t * ui_Container8;
extern lv_obj_t * ui_AccelLabel6;
extern lv_obj_t * ui_Roll;
extern lv_obj_t * ui_Container9;
extern lv_obj_t * ui_AccelLabel7;
extern lv_obj_t * ui_Pitch;
extern lv_obj_t * ui_Container10;
extern lv_obj_t * ui_AccelLabel8;
extern lv_obj_t * ui_Yaw;
extern void ui_event_Button4(lv_event_t * e);
extern lv_obj_t * ui_Button4;
extern lv_obj_t * ui_Label5;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

