// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"


///////////////////// SCREENS ////////////////////

#include "screens/ui_MainScreen.h"
#include "screens/ui_ScreenMenu.h"
#include "screens/ui_ScreenAccel.h"

///////////////////// VARIABLES ////////////////////


// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_1966217086);    // assets/d31cfea5-24e3-4a81-b4ce-13c598e2818d.png

// FONTS
LV_FONT_DECLARE(ui_font_FontAwesomepro6light20);
LV_FONT_DECLARE(ui_font_FontAwesomepro6light30);
LV_FONT_DECLARE(ui_font_FontAwesomepro6lightSmall);
LV_FONT_DECLARE(ui_font_FontAwesomepro6solid20);
LV_FONT_DECLARE(ui_font_roboto14);

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
