// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"


///////////////////// SCREENS ////////////////////

#include "screens/ui_MainScreen.h"
#include "screens/ui_ScreenMenu.h"
#include "screens/ui_ScreenAccel.h"

///////////////////// VARIABLES ////////////////////


// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_1882603517);    // assets/assets-2.png
LV_IMG_DECLARE(ui_img_942215904);    // assets/gauge-bg.png
LV_IMG_DECLARE(ui_img_1798728470);    // assets/gauge-indicator.png
LV_IMG_DECLARE(ui_img_1601502596);    // assets/gauge-needle.png
LV_IMG_DECLARE(ui_img_scull_png);    // assets/scull.png

// FONTS
LV_FONT_DECLARE(ui_font_FontRoboto12);
LV_FONT_DECLARE(ui_font_FontRoboto20);
LV_FONT_DECLARE(ui_font_FontSpeed);

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
