// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

void AccelScreenLoadEvent(lv_event_t *e)
{
	// Your code here
}

void AccelScreenUnloadEvent(lv_event_t *e)
{
	// Your code here
}

void slider1_event_handler(lv_event_t * e)
{
	// Your code here
}

void slider2_event_handler(lv_event_t * e)
{
	// Your code here
}
