// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _UI_COMP_ONOFFCOMP_H
#define _UI_COMP_ONOFFCOMP_H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT OnOffComp
#define UI_COMP_ONOFFCOMP_ONOFFCOMP 0
#define UI_COMP_ONOFFCOMP_SWITCH1 1
#define UI_COMP_ONOFFCOMP_CONTAINER19 2
#define UI_COMP_ONOFFCOMP_CONTAINER19_LABEL11 3
#define UI_COMP_ONOFFCOMP_CONTAINER19_LABEL12 4
#define _UI_COMP_ONOFFCOMP_NUM 5
lv_obj_t * ui_OnOffComp_create(lv_obj_t * comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
